### ISSUE TITLE
I can't reproduce success！

### ISSUE THREAD

**Issue by Ckmount** [brianwrf/WordPress_4.9.8_RCE_POC#1]
When I went to step 7：
Repeat the POST request /wp-admin/admin-ajax.php captured in step 5 in Burp Repeater;
![image](https://user-images.githubusercontent.com/18661632/53780275-a0371f00-3f3e-11e9-98a5-b0554d81ddcb.png)
I can't get the same response as you.
can you help me?

**Comment by akat12** [comment]
Same issue. I am unable to recreate this with imagick. The issue being that the imagedit-preview fails for any crop requests once the image post meta variable is modified as imagick is no longer able to find it. As for GD the directory traversal works as stated but getting a crafted payload is difficult due to gd stripping image data and compression.

**Comment by brianwrf** [comment]
Same as [#2](https://github.com/brianwrf/WordPress_4.9.8_RCE_POC/issues/2)
