### ISSUE TITLE
I can't reproduce step 7! error: Unable to create new image

### ISSUE THREAD

**Issue by adsnjhfyeqw231eas** [brianwrf/WordPress_4.9.8_RCE_POC#2]
When I went to step 7：
Repeat the POST request /wp-admin/admin-ajax.php captured in step 5 in Burp Repeater;
![capture](https://user-images.githubusercontent.com/8340935/53860155-118dd500-4006-11e9-91ea-39c9419cb518.PNG)
@brianwrf I can't get the same response as you.
can you help me?

**Comment by akat12** [comment]
I am unable to recreate this with imagick. The issue being that the imagedit-preview fails for any crop requests once the image post meta variable is modified as imagick is no longer able to find it. As for GD the directory traversal works as stated but getting a crafted payload is difficult due to gd stripping image data and compression.

**Comment by akat12** [comment]
Same as #1

**Comment by brianwrf** [comment]
Please use `&meta_input[_wp_attached_file]=<CURRENT YEAR>/<CURRENT MONTH>/poc.jpg#/poc.jpg`, e.g. `&meta_input[_wp_attached_file]=2019/02/poc.jpg#/poc.jpg` for February. In your case, it should be `&meta_input[_wp_attached_file]=2019/03/poc.jpg#/poc.jpg` since the current month is `03` rather than `02`.

**Comment by Ckmount** [comment]
> Please use `&meta_input[_wp_attached_file]=<CURRENT YEAR>/<CURRENT MONTH>/poc.jpg#/poc.jpg`, e.g. `&meta_input[_wp_attached_file]=2019/02/poc.jpg#/poc.jpg` for February. In your case, it should be `&meta_input[_wp_attached_file]=2019/03/poc.jpg#/poc.jpg` since the current month is `03` rather than `02`.

Not for this reason, it's the plugin problem.

**Comment by brianwrf** [comment]
@TeemoCaptain1234 I don't think so for my docker image. I've pre-installed PHP-Imagick for the wordpress site in the image. I didn't see the error on my side either.

**Comment by akat12** [comment]
Could you specify your imagine version? And I was changing the year and
month for the requests.

**Comment by akat12** [comment]
Imagick*

**Comment by brianwrf** [comment]
@akat12 It appears to be ImageMagick 6.8.9. But again, I don't think it is the Imagick issue.

**Comment by akat12** [comment]
Ok so i  have figured it out. @TridevGuha @TeemoCaptain1234 @brianwrf . This vuln works on a LAMP stack and fails on WAMP for imagick. must be something to do with the php_imagick dll i reckon. If gd is the image editor the directory traversal still works.
